### ISSUE TITLE
Compilation error: ‘ZWARN_INVALID_OPTION’

### ISSUE THREAD

**Issue by GHNewbiee** [davidbeauchamp/pgzint#2]
Hi,

I use **PostgreSQL 10.1**, and have had **zint-2.6.2** compiled and installed successfully.

After that, when I am trying to have **pgzint** compiled, I get the following error:

```
pgzint.c:171:18: error: ‘ZWARN_INVALID_OPTION’ undeclared (first use in this function)
```

Any advice or suggestion, please?!

Tia

**Comment by davidbeauchamp** [comment]
Hello there, 

Thank you for trying out PG 10.1, you beat me to it actually and have not seen this yet. I had last built with zint 2.4something if I recall semi-correctly and the headers may have changed. I will test this out, in the interim you can try changing ZWARN_INVALID_OPTION to 2 as that is what the constant represented. It should get you built for now until I can see how the zint interface changed.

David

**Comment by davidbeauchamp** [comment]
Looks like that changed to ZINT_WARN_INVALID_OPTION with zint-2.6.2, if you wanted to change it to the official new constant that is it. I can get a commit in to fix it but please let me know how you make out.

**Comment by davidbeauchamp** [comment]
Fixed by https://github.com/davidbeauchamp/pgzint/commit/89fe2f27de1cdd77031cb494d66f5955b9b1fb13
